// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoYBPWZYikuQmz37Nd1XrYU0MJxaMR2g',
    appId: '1:791160633379:web:12131c9a0f2aeb753f1996',
    messagingSenderId: '791160633379',
    projectId: 'gym-app-tfg',
    authDomain: 'gym-app-tfg.firebaseapp.com',
    storageBucket: 'gym-app-tfg.appspot.com',
    measurementId: 'G-TZBRYYCSBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSo4_xoLGm9KVPWRu0aU3s_flj7dqkbZw',
    appId: '1:791160633379:android:3186d8e2dab5779e3f1996',
    messagingSenderId: '791160633379',
    projectId: 'gym-app-tfg',
    storageBucket: 'gym-app-tfg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkl3y1Xn1owca-KK8Kb_z10FLmFEKdVAU',
    appId: '1:791160633379:ios:415d8533f9d8cb203f1996',
    messagingSenderId: '791160633379',
    projectId: 'gym-app-tfg',
    storageBucket: 'gym-app-tfg.appspot.com',
    iosBundleId: 'com.example.gymAppTfg',
  );
}
